// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compute_dominant_frequency`, `compute_loudness`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

FartAnalysisResult analyzeFart(
        {required List<double> samples, required double sampleRate}) =>
    RustLib.instance.api
        .crateApiAnalyzerAnalyzeFart(samples: samples, sampleRate: sampleRate);

/// Structure to return analysis results
class FartAnalysisResult {
  final double loudnessDb;
  final double duration;
  final double dominantFreq;

  const FartAnalysisResult({
    required this.loudnessDb,
    required this.duration,
    required this.dominantFreq,
  });

  @override
  int get hashCode =>
      loudnessDb.hashCode ^ duration.hashCode ^ dominantFreq.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FartAnalysisResult &&
          runtimeType == other.runtimeType &&
          loudnessDb == other.loudnessDb &&
          duration == other.duration &&
          dominantFreq == other.dominantFreq;
}
